<?php

namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\JsonResource;
use Illuminate\Support\Facades\Auth;

class UserCollection extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function toArray($request)
    {
        $data = [
            'id' => $this->id,
            'name' => $this->name,
            'email' => $this->email,
            'test' => 'This is just a test', //Giả sử ta cần thêm thuộc tính test.
            // return field "secret" has value "secret-value" if condition true
            'secret' => $this->when(false, 'secret-value'),
            $this->mergeWhen(true, [
                'first-secret' => 'value',
                'second-secret' => 'value',
            ]),
            // end of this above
            'created_at' => (string)$this->created_at,
            'updated_at' => $this->updated_at, // ép kiểu
        ];
        return $data;
    }

    // remove option withoutWrapping
    public function with($request)
    {
        return [
            'meta' => [
                'key' => 'value',
            ],
        ];
    }

    public function withResponse($request, $response)
    {
        $response->header('X-Value', 'True');
//        parent::withResponse($request, $response); // TODO: Change the autogenerated stub
    }
}
